services:
  fastapi_app:
    build:
      context: ./backend
      dockerfile: Dockerfile-local
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
      - ./backend/alembic.ini:/app/alembic.ini
    working_dir: /app
    command: ["uv", "run", "uvicorn", "--factory", "src.main:create_app", "--reload",
      "--host", "0.0.0.0", "--port", "8000", ]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - local

  postgres:
    image: postgres:17.3-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local
    restart: unless-stopped

networks:
  local:
    driver: bridge

volumes:
  postgres_data:
