services:
  fastapi_app:
    build:
      context: ./backend
      dockerfile: Dockerfile-local
    container_name: app
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
      - ./backend/alembic.ini:/app/alembic.ini
    working_dir: /app
    command: ["uv", "run", "uvicorn", "--factory", "src.main:create_app", "--reload",
      "--host", "0.0.0.0", "--port", "8000", ]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
      - loki
      - tempo
    networks:
      - local
    labels:
      logging: "promtail"

  postgres:
    image: postgres:17.3-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local
    restart: unless-stopped
    labels:
      logging: "promtail"

  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - fastapi_app
    networks:
      - local
    restart: unless-stopped
    labels:
      logging: "promtail"

  redis:
    image: redis:8.2-alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - local
    restart: unless-stopped
#    command: redis-server --appendonly yes  # --appendonly yes если хотите сохранять данные Redis.

  taskiq_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile-local
    container_name: taskiq_worker
    working_dir: /app
    command: [
      "uv",
      "run",
      "taskiq",
      "worker",
      "src.config.broker:broker",
      "src.infrastructure.taskiq.tasks.schedule_tasks",
      "--fs-discover",
      "--workers",
      "3",
      "--log-level",
      "INFO"
    ]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    networks:
      - local
    volumes:
      - ./backend/src:/app/src
    labels:
      logging: "promtail"

  taskiq_scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile-local
    container_name: taskiq_scheduler
    working_dir: /app
    command: [
      "uv",
      "run",
      "taskiq",
      "scheduler",
      "src.config.broker:scheduler",
      "src.infrastructure.taskiq.tasks.schedule_tasks",
      "--log-level",
      "INFO"
    ]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - local
    volumes:
      - ./backend/src:/app/src
    labels:
      logging: "promtail"

  # ==========================================
  # PLG STACK (Monitoring)
  # ==========================================

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./backend/observability/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
    networks:
      - local

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./backend/observability/promtail-config.yaml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    networks:
      - local

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - prometheus
      - tempo
    networks:
      - local
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v3.8.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./backend/observability/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle' # Позволяет перезагружать конфиг на лету
    networks:
      - local
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    user: root
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./backend/observability/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"   # Порт для админки/метрик
      - "4317:4317"   # OTLP gRPC (сюда шлет Python)
      # - "4318:4318" # OTLP HTTP (альтернатива)
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  grafana_data:
  loki_data:
  prometheus_data:
  tempo_data:
