services:
  fastapi_app:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    command: ["uv", "run", "-m", "src.main",]
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - local

networks:
  local:
    driver: bridge
