FROM ghcr.io/astral-sh/uv:python3.13-bookworm-slim

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy

COPY pyproject.toml uv.lock /app/

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-dev

COPY src /app/backend/src/

ENV PYTHONPATH=/app
ENV PATH="/app/.venv/bin/:$PATH"

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
# uvicorn --factory src.main:create_app --reload --host 0.0.0.0 --port 8000
