# src/shared/error_codes.py
from enum import Enum


class ErrorCode(Enum):
    """Коды ошибок для всего приложения."""

    # Общие ошибки
    BASE_APPLICATION_ERROR = "BASE_APPLICATION_ERROR"
    APPLICATION_ERROR = "APPLICATION_ERROR"
    USE_CASE_ERROR = "USE_CASE_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION"

    # Инфраструктурные ошибки
    DATABASE_TIMEOUT = "DATABASE_TIMEOUT"
    DATABASE_ERROR = "DATABASE_ERROR"
    DATA_INTEGRITY_ERROR = "DATA_INTEGRITY_ERROR"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"

    # Ошибки сущностей
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    CONCURRENT_MODIFICATION = "CONCURRENT_MODIFICATION"
    DUPLICATE_ENTITY = "DUPLICATE_ENTITY"
    USER_ALREADY_EXIST = "USER_ALREADY_EXIST"

    def __str__(self):
        return self.value
